name: Repo Mirror CI

on:
  push:

jobs:
  to_epitech:
    runs-on: ubuntu-latest
    steps:
        uses: actions/checkout@v2
        with:
            fetch-depth: 0

      - name: Get current branch
        id: branch
        run: echo ::set-output name=branch::$(git rev-parse --abbrev-ref HEAD)

    - name: Push to the same branch in another repository
      uses: pixta-dev/repository-mirroring-action@v1
      with:
        github_token: ${{ secrets.PAT_TOKEN }}
        branch: ${{ steps.branch.outputs.branch }} # Utilisez la même branche que celle surveillée dans le dépôt source
        repository: axFury/testrtype.git